version: '3.8'

services:
  pinstle:
    build:
      context: .
      dockerfile: Dockerfile.autobuild
    ports:
      - "9002:80"
    environment:
      - SECRET_KEY=${SECRET_KEY}
      - ALLOWED_HOSTS=${ALLOWED_HOSTS}
    volumes:
      - /var/lib/docker/volumes/2f2434a82a88a1b64219c8bb6f59751581bcc4ff2eca9a81b5d2e53866873cc2:/data
    restart: unless-stopped

volumes:
  pinry_data:
